---
title: "Probability"
sidebar: false
---

Welcome to the website for Middlebury College's Spring 2025 MATH/STAT 310. On this website you will find the course syllabus, schedule, and assignments. The website is frequently updated during the semester, so please make a habit of refreshing the page. The icons at the top right will link to the online version of the textbook and Canvas.

## Major Announcements

-   Math & Stats pre-registration [dessert social](dessert_social.pdf)!
    -   Monday 4/14 3:00-4:30pm in WNS 105
    -   Come here about upcoming classes, receive advice, and eat dessert!
-   Homework 6 due date pushed back one day to Wednesday, 4/09!
-   Midterm revisions:
    -   You're welcome to revise any/all problems *in their entirety* for some points back. Exact amount of points back depends on the problem and the quality of revision.
    -   Please do your revisions on a separate piece of paper. Then submit your revisions attached to your original midterm by **Thursday at 5pm**.
        -   If I'm around the office, feel free to hand them to me directly. If I'm not in the office, I'll leave a folder outside my door. No peeking!
    -   You're welcome to come chat with me about questions! The purpose of the revisions is to give you an opportunity to better understand the course material. I don't recommend getting solutions from others because that will only hurt you in the long run.

## Course Details

Instructor: Becky Tang

-   Office: WNS 214
-   Email: btang\@middlebury.edu

Meeting times: MWF 8:40-9:30am in WNS 105

Office hours: MT 3-4pm, F 11am-12pm (outside my office)

[Syllabus](310_syllabus.pdf) (most recent update: 02/07/25)
